---
- name: Gather all VMs for vCenter
  gather_facts: no
  vars_files:
  - vsphere.yaml
  hosts: localhost
  tasks:
  - name: Login into vCenter
    uri:
      url: https://{{ vcenter_server }}/rest/com/vmware/cis/session
      force_basic_auth: yes
      validate_certs: no
      method: POST
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
    register: login
  - name: Get VMs from vCenter
    uri:
        url: https://{{ vcenter_server }}/rest/vcenter/vm
        force_basic_auth: yes
        validate_certs: no
        headers:
          Cookie: "{{ login.set_cookie }}"
    register: vVMs

  - name: Print names of VMs in the given vCenter
    debug:
        msg: "{{ item.name }}"
    with_items: "{{ vVMs.json.value }}"
